query($categories: [String], $manufacturers: [String], $title: String, $language_id: ID) {
  getAircraftPosts(categories: $categories, manufacturers: $manufacturers, title: $title, language_id: $language_id) {
    posts {
      __typename
        ... on PostInterface {
        id
        slug
        post_id
        summary
        publish_at
        title
        type
        meta
        media {
          id
          src
        }
        body
    

        __typename
        ... on Article {
          taxonomies {
            taxonomy
            term {
              id
              name
            }
          }
        }
          
        __typename
        ... on Aircraft {
          details
          taxonomies {
            taxonomy
            term {
              id
              name
            }
          }
        }
        
        __typename
        ... on Destination {
          taxonomies {
            taxonomy
            term {
              id
              name
            }
          }
        }
        
        __typename
        ... on Event {
          taxonomies {
            taxonomy
            term {
              id
              name
            }
          }
        }
        
        __typename
        ... on Office {
          taxonomies {
            taxonomy
            term {
              id
              name
            }
          }
        }
        
        __typename
        ... on Page {
          taxonomies {
            taxonomy
            term {
              id
              name
            }
          }
        }
        
        __typename
        ... on TeamMember {
          taxonomies {
            taxonomy
            term {
              id
              name
            }
          }
        }
    	}
      
    }
    term {
      id
      name
      slug
    }
  }
}