query($iata: [String], $other_destinations: [String], $city_id: String) {
  sfAirports: getSFAirports(iata: $iata) {
    sfid
    name
    icao
    iata
    coordinates
    city {
      name
      name_en
      name_de
      name_it
      name_fr
      name_es
      name_ru
      name_pl
      name_hu
      coordinates
      country {
        countryCode
        name
      }
    }
  },
  other_destinations: getAirportsByPosts(post_ids: $other_destinations) {
    sfid
    post
    city {
      name
    }
  },
  city: getSFAirportCity(sfid: $city_id) {
    name
    sfid
    coordinates
    country{
      name
      countryCode
    }
  }
}