export const START_FETCHING_ACCOUNTS = "START_FETCHING_ACCOUNTS";
export const FETCHING_ACCOUNTS_SUCCESS = "FETCHING_ACCOUNTS_SUCCESS";
export const FETCHING_ACCOUNTS_ERROR = "FETCHING_ACCOUNTS_ERROR";
