export const START_FETCHING_AIRPORTS = "START_FETCHING_AIRPORTS";
export const FETCHING_AIRPORTS_SUCCESS = "FETCHING_AIRPORTS_SUCCESS";
export const FETCHING_AIRPORTS_ERROR = "FETCHING_AIRPORTS_ERROR";
export const FETCHING_SFAIRPORTS_SUCCESS = "FETCHING_SFAIRPORTS_SUCCESS";