export const START_FETCHING_CATEGORIES = "START_FETCHING_CATEGORIES";
export const FETCHING_CATEGORIES_SUCCESS = "FETCHING_CATEGORIES_SUCCESS";
export const FETCHING_CATEGORIES_ERRORS = "FETCHING_CATEGORIES_ERRORS";
