export const START_FETCHING_CITIES = "START_FETCHING_CITIES";
export const FETCHING_CITIES_SUCCESS = "FETCHING_CITIES_SUCCESS";
export const FETCHING_CITIES_ERRORS = "FETCHING_CITIES_ERRORS";
export const FETCHING_CITIES_EDITOR_SUCCESS = "FETCHING_CITIES_EDITOR_SUCCESS";
export const FETCHING_CITIES_SELECTED_SUCCESS = "FETCHING_CITIES_SELECTED_SUCCESS";