export const START_FETCHING_DESTINATIONS = "START_FETCHING_DESTINATIONS";
export const FETCHING_DESTINATIONS_SUCCESS = "FETCHING_DESTINATIONS_SUCCESS";
export const FETCHING_DESTINATIONS_ERRORS = "FETCHING_DESTINATIONS_ERRORS";
export const DESTINATIONS_REMOVE_VISIBILITY_FILTER = "DESTINATIONS_REMOVE_VISIBILITY_FILTER";
export const DESTINATIONS_SET_VISIBILITY_FILTER = "DESTINATIONS_SET_VISIBILITY_FILTER";
export const ADD_DESTINATION = "ADD_DESTINATION";
export const ADD_DESTINATION_SUCCESS = "ADD_DESTINATION_SUCCESS";
export const ADD_DESTINATION_ERROR = "ADD_DESTINATION_ERROR";
export const EDIT_DESTINATION = "EDIT_DESTINATION";
export const EDIT_DESTINATION_SUCCESS = "EDIT_DESTINATION_SUCCESS";
export const EDIT_DESTINATION_ERROR = "EDIT_DESTINATION_ERROR";

export const REMOVE_DESTINATION = "REMOVE_DESTINATION";
export const REMOVE_DESTINATION_SUCCESS = "REMOVE_DESTINATION_SUCCESS";
export const REMOVE_DESTINATION_ERROR = "REMOVE_DESTINATION_ERROR";
export const REMOVE_DESTINATION_TRANSLATION = "REMOVE_DESTINATION_TRANSLATION";
export const REMOVE_DESTINATION_TRANSLATION_SUCCESS = "REMOVE_DESTINATION_TRANSLATION_SUCCESS";
export const REMOVE_DESTINATION_TRANSLATION_ERROR = "REMOVE_DESTINATION_TRANSLATION_ERROR";
