export const REMOVE_EMAIL_TEMPLATE = "REMOVE_EMAIL_TEMPLATE";
export const REMOVE_EMAIL_TEMPLATE_SUCCESS = "REMOVE_EMAIL_TEMPLATE_SUCCESS";
export const REMOVE_EMAIL_TEMPLATE_ERROR = "REMOVE_EMAIL_TEMPLATE_ERROR";
export const REMOVE_EMAIL_TEMPLATE_TRANSLATION = "REMOVE_EMAIL_TEMPLATE_TRANSLATION";
export const REMOVE_EMAIL_TEMPLATE_TRANSLATION_SUCCESS = "REMOVE_EMAIL_TEMPLATE_TRANSLATION_SUCCESS";
export const REMOVE_EMAIL_TEMPLATE_TRANSLATION_ERROR = "REMOVE_EMAIL_TEMPLATE_TRANSLATION_ERROR";