export const FETCH_REDIRECTIONS = 'FETCH_REDIRECTIONS';
export const FETCH_REDIRECTIONS_SUCCESS = 'FETCH_REDIRECTIONS_SUCCESS';
export const FETCH_REDIRECTIONS_ERROR = 'FETCH_REDIRECTIONS_ERROR';
export const UPDATE_REDIRECTION = 'UPDATE_REDIRECTION';
export const UPDATE_REDIRECTION_SUCCESS = 'UPDATE_REDIRECTION_SUCCESS';
export const UPDATE_REDIRECTION_ERROR = 'UPDATE_REDIRECTION_ERROR';
export const CREATE_REDIRECTION = 'CREATE_REDIRECTION';
export const CREATE_REDIRECTION_SUCCESS = 'CREATE_REDIRECTION_SUCCESS';
export const CREATE_REDIRECTION_ERROR = 'CREATE_REDIRECTION_ERROR';
export const REMOVE_REDIRECTION = 'REMOVE_REDIRECTION';
export const REMOVE_REDIRECTION_SUCCESS = 'REMOVE_REDIRECTION_SUCCESS';
export const REMOVE_REDIRECTION_ERROR = 'REMOVE_REDIRECTION_ERROR';

