export const FETCH_SETTINGS = "FETCH_SETTINGS";
export const FETCH_SETTINGS_SUCCESS = "FETCH_SETTINGS_SUCCESS";
export const FETCH_SETTINGS_ERROR = "FETCH_SETTINGS_ERROR";

export const UPDATE_SETTINGS_OPTION = "UPDATE_SETTINGS_OPTION";
export const UPDATE_SETTINGS_OPTION_SUCCESS = "UPDATE_SETTINGS_OPTION_SUCCESS";
export const UPDATE_SETTINGS_OPTION_ERROR = "UPDATE_SETTINGS_OPTION_ERROR";

export const FETCH_SENSITIVE_SETTINGS = 'FETCH_SENSITIVE_SETTINGS';
export const FETCH_SENSITIVE_SETTINGS_SUCCESS = 'FETCH_SENSITIVE_SETTINGS_SUCCESS';
export const FETCH_SENSITIVE_SETTINGS_ERROR = 'FETCH_SENSITIVE_SETTINGS_ERROR';