export const START_FETCHING_PERMISSIONS = "START_FETCHING_PERMISSIONS";
export const FETCHING_PERMISSIONS_SUCCESS = "FETCHING_PERMISSIONS_SUCCESS";
export const FETCHING_PERMISSIONS_ERROR = "FETCHING_PERMISSIONS_ERROR";
