/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const START_REQFLIGHT = 'START_REQFLIGHT';
export const STOP_REQFLIGHT = 'STOP_REQFLIGHT';

export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';
export const SET_CURRENCY_START = 'SET_CURRENCY_START';
export const SET_CURRENCY_SUCCESS = 'SET_CURRENCY_SUCCESS';
export const SET_CURRENCY_ERROR = 'SET_CURRENCY_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SET_STICKY = 'SET_STICKY';

export const SET_AVAILABLE_LOCALES = 'SET_AVAILABLE_LOCALES';

export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES';
export const GET_ALL_ARTICLES_SUCCESS = 'GET_ALL_ARTICLES_SUCCESS';
export const GET_ALL_ARTICLES_ERROR = 'GET_ALL_ARTICLES_ERROR';
export const GET_SINGLE_ARTICLE = 'GET_SINGLE_ARTICLE';
export const GET_SINGLE_ARTICLE_ERROR = 'GET_SINGLE_ARTICLE_ERROR';
export const GET_SINGLE_ARTICLE_SUCCESS = 'GET_SINGLE_ARTICLE_SUCCESS';
export const CREATE_NEW_ARTICLE = 'CREATE_NEW_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const SELECT_ARTICLE = 'SELECT_ARTICLE';

export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
export const GET_ALL_EVENTS_ERROR = 'GET_ALL_EVENTS_ERROR';
export const GET_SINGLE_EVENT = 'GET_SINGLE_EVENT';
export const GET_SINGLE_EVENT_ERROR = 'GET_SINGLE_EVENT_ERROR';
export const GET_SINGLE_EVENT_SUCCESS = 'GET_SINGLE_EVENT_SUCCESS';
export const CREATE_NEW_EVENT = 'CREATE_NEW_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const SELECT_EVENT = 'SELECT_EVENT';

export const CUSTOMER_LOGIN_START = 'CUSTOMER_LOGIN_START';
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_ERROR = 'CUSTOMER_LOGIN_ERROR';
export const LOGOUT_CUSTOMER = 'LOGOUT_CUSTOMER';
export const CREATE_CUSTOMER_START = 'CREATE_CUSTOMER_START';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';

export const GET_CHAT_ROOMS = 'GET_CHAT_ROOMS';
export const GET_CHAT_ROOMS_SUCCESS = 'GET_CHAT_ROOMS_SUCCESS';
export const GET_CHAT_ROOMS_ERROR = 'GET_CHAT_ROOMS_ERROR';

export const GET_SINGLE_CHAT_ROOM = 'GET_SINGLE_CHAT_ROOM';
export const GET_SINGLE_CHAT_ROOM_SUCCESS = 'GET_SINGLE_CHAT_ROOM_SUCCESS';
export const GET_SINGLE_CHAT_ROOM_ERROR = 'GET_SINGLE_CHAT_ROOM_ERROR';
export const ADD_CHAT_ROOM = 'ADD_CHAT_ROOM';
export const UPDATE_CHAT_ROOM = 'UPDATE_CHAT_ROOM';
export const ADD_MESSAGE_TO_CHAT_ROOM = 'ADD_MESSAGE_TO_CHAT_ROOM';

export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_SET_AVATAR = 'USER_SET_AVATAR';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const SET_USER_ERROR = 'SET_USER_ERROR';

export const SET_SETTINGS = 'SET_SETTINGS';
export const SET_SETTINGS_ERROR = 'SET_SETTINGS_ERROR';
export const UPDATE_OPTION = 'UPDATE_OPTION';
export const UPDATE_SETTINGS_ERROR = 'UPDATE_SETTINGS_ERROR';

export const ADD_PAGE = 'ADD_PAGE';
export const CREATE_PAGE = 'CREATE_PAGE';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const SET_PAGES = 'SET_PAGES';
export const INJECT_PAGE = 'INJECT_PAGE';

export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';
export const SET_TEMPLATES = 'SET_TEMPLATES';

export const CREATE_OFFICE = 'CREATE_OFFICE';
export const UPDATE_OFFICE = 'UPDATE_OFFICE';
export const SET_OFFICES = 'SET_OFFICES';
export const REMOVE_OFFICE = 'REMOVE_OFFICE';
export const REORDER_OFFICE = 'REORDER_OFFICE';

export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_MEMBER = 'CREATE_TEAM_MEMBER';
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const SET_TEAMS = 'SET_TEAMS';
export const REMOVE_TEAM = 'REMOVE_TEAM';
export const REORDER_TEAM = 'REORDER_TEAM';
export const REORDER_TEAM_MEMBER = 'REORDER_TEAM_MEMBER';

export const SET_SELECTED_COMPONENT = 'SET_SELECTED_COMPONENT';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const REMOVE_COMPONENT = 'REMOVE_COMPONENT';
export const SAVE_PAGE = 'SAVE_PAGE';
export const DEFINE_COMPONENT_TARGET = 'DEFINE_COMPONENT_TARGET';

export const SIDEBAR_TOGGLE_SETTINGS = 'SIDEBAR_TOGGLE_SETTINGS';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const SET_ALL_ROLES = 'SET_ALL_ROLES';
export const SET_ALL_REDIRECTIONS = 'SET_ALL_REDIRECTIONS';
export const ADD_REDIRECT_SUCCESS = 'ADD_REDIRECT_SUCCESS';
export const UPDATE_REDIRECTION = 'UPDATE_REDIRECTION';
export const REMOVE_REDIRECT_SUCCESS = 'REMOVE_REDIRECT_SUCCESS';
export const TOGGLE_SELECTION = 'TOGGLE_SELECTION';
export const SELECT_USERS = 'SELECT_USERS';

export const REORDER_CHILD = 'REORDER_CHILD';
export const CREATE_NODE = 'CREATE_NODE';
export const DELETE_NODE = 'DELETE_NODE';
export const ADD_CHILD = 'ADD_CHILD';
export const REMOVE_CHILD = 'REMOVE_CHILD';
export const SET_BODY = 'SET_BODY';
export const UPDATE_CHILD = 'UPDATE_CHILD';
export const UPDATE_ROOT = 'UPDATE_ROOT';
export const UPDATE_ROOT_CSS = 'UPDATE_ROOT_CSS';
export const REMOVE_ROOT_CSS = 'REMOVE_ROOT_CSS';
export const ADD_CHILD_CLASS = 'UPDATE_CHILD_CLASS';
export const REMOVE_CHILD_CLASS = 'REMOVE_CHILD_CLASS';
export const UPDATE_STYLE_SHEET = 'UPDATE_STYLE_SHEET';
export const SET_EDITOR_LOCALE = 'SET_EDITOR_LOCALE';
export const SET_EDITOR_LOCALE_ERROR = 'SET_EDITOR_LOCALE_ERROR';

export const SET_ALL_RATES = 'SET_ALL_RATES';
export const UPDATE_RATE = 'UPDATE_RATE';

export const SET_LOCALES = 'SET_LOCALES';
export const SET_TRANSLATIONS = 'SET_TRANSLATIONS';
export const ADD_LANGUAGE = 'ADD_LANGUAGE';
export const REMOVE_LANGUAGE = 'REMOVE_LANGUAGE';
export const SET_LANGUAGE_ENABLED = 'SET_LANGUAGE_ENABLED';
export const UPDATE_TRANSLATION = 'UPDATE_TRANSLATION';

export const START_UPLOAD = 'START_UPLOAD';
export const END_UPLOAD = 'END_UPLOAD';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const SET_MEDIA = 'SET_MEDIA';

export const TOGGLE_BACKDROP = 'TOGGLE_BACKDROP';
export const SHOW_BACKDROP = 'SHOW_BACKDROP';
export const HIDE_BACKDROP = 'HIDE_BACKDROP';

export const TOGGLE_NAV = 'TOGGLE_NAV';
export const SHOW_NAV = 'SHOW_NAV';
export const HIDE_NAV = 'HIDE_NAV';
export const SELECT_IN_TABLE = 'SELECT_IN_TABLE';

export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';

export const SET_CURRENTTALK = 'SET_CURRENTTALK';
export const TOGGLE_CURRENTTALK = 'TOGGLE_CURRENTTALK';
export const SELECT_ROOM = 'SELECT_ROOM';

export const RTC_SET_SOCKET = 'RTC_SET_SOCKET';
export const RTC_CONNECTED = 'RTC_CONNECTED';
export const RTC_CONNECTING = 'RTC_CONNECTING';
export const RTC_DISCONNECTED = 'RTC_DISCONNECTED';
export const RTC_SOCKET_UNAVAILABLE = 'RTC_SOCKET_UNAVAILABLE';
export const RTC_SOCKET_AVAILABLE = 'RTC_SOCKET_AVAILABLE';
