export const RTC_CONNECTED = 'RTC_CONNECTED';
export const RTC_CONNECTING = 'RTC_CONNECTING';
export const RTC_DISCONNECTED = 'RTC_DISCONNECTED';
export const RTC_SOCKET_UNAVAILABLE = 'RTC_SOCKET_UNAVAILABLE';
export const RTC_SOCKET_AVAILABLE = 'RTC_SOCKET_AVAILABLE';
export const RTC_SET_SOCKET = 'RTC_SET_SOCKET';