export const GET_REVIEWS_START = 'GET_REVIEWS_START';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';
export const GET_AIRCRAFT_TAXONOMIES_START = 'GET_AIRCRAFT_TAXONOMIES_START';
export const GET_AIRCRAFT_TAXONOMIES_SUCCESS = 'GET_AIRCRAFT_TAXONOMIES_SUCCESS';
export const GET_AIRCRAFT_TAXONOMIES_ERROR = 'GET_AIRCRAFT_TAXONOMIES_ERROR';