export const FETCH_IP_INFO = 'FETCH_IP_INFO';
export const START_FETCHING_IP_INFO = 'START_FETCHING_IP_INFO';
export const STOP_FETCHING_IP_INFO = 'STOP_FETCHING_IP_INFO';
export const FETCH_IP_INFO_FAILED = 'FETCH_IP_INFO_FAILED';
export const FETCH_IP_INFO_SUCCESS = 'FETCH_IP_INFO_SUCCESS';
export const SET_IP_INFO = 'SET_IP_INFO';