export const UPDATE_OR_CREATE_MEDIA_REFERENCE = 'UPDATE_OR_CREATE_MEDIA_REFERENCE';
export const UPDATE_OR_CREATE_MEDIA_REFERENCE_SUCCESS = 'UPDATE_OR_CREATE_MEDIA_REFERENCE_SUCCESS';
export const UPDATE_OR_CREATE_MEDIA_REFERENCE_ERROR = 'UPDATE_OR_CREATE_MEDIA_REFERENCE_ERROR';
export const SET_RICH_MEDIA_LIST_START = 'SET_RICH_MEDIA_LIST_START';
export const SET_RICH_MEDIA_LIST_SUCCESS = 'SET_RICH_MEDIA_LIST_SUCCESS';
export const SET_RICH_MEDIA_LIST_ERROR = 'SET_RICH_MEDIA_LIST_ERROR';